apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data-pv
spec:
  capacity:
    storage: 3500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-nas
  mountOptions:
    - nfsvers=3
    - hard
    - timeo=600
    - retrans=3
  nfs:
    server: 192.168.178.200
    path: /volume1/nextcloud
