apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-nas
  resources:
    requests:
      storage: 3500Gi
  volumeName: nextcloud-data-pv
