apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frigate-nvr
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/blakeblackshear/blakeshome-charts
    chart: frigate
    targetRevision: 7.8.0
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/slin86/argocd/refs/heads/main/apps/frigate-nvr/my-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: frigate-nvr
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
