apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frigate-nvr
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/blakeblackshear/blakeshome-charts
    targetRevision: HEAD
    path: charts/frigate
    helm:
      values: |
        frigate:
          detectors:
            cpu1:
              type: cpu
          logger:
            default: debug
        
          mqtt:
            host: mqtt-mosquitto.mqtt.svc.cluster.local
            port: 1883
            topic_prefix: frigate
            client_id: frigate

          cameras:
            garten:
              ffmpeg:
                inputs:
                  - path: rtsp://admin:N3C-iAJf8g_ZaQZwEEY@@192.168.178.90:554/h264Preview_01_main
                    roles:
                      - detect
                      - record
              detect:
                width: 3840
                height: 2160
                fps: 5
              objects:
                track:
                  - person
                  - dog

          record:
            enabled: true
            events:
              retain:
                days: 3

        persistence:
          config:
            enabled: true
            size: 1Gi
          media:
            enabled: true
            size: 1536Gi
            accessMode: ReadWriteOnce

        service:
          main:
            type: NodePort
            ports:
              http:
                port: 5000

  destination:
    server: https://kubernetes.default.svc
    namespace: frigate-nvr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
