apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: mongodb
    targetRevision: 14.4.5
    helm:
      valueFiles:
        - https://github.com/slin86/argocd/apps/mongodb/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: omada
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
