apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frigate
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/slin86/argocd
    targetRevision: HEAD
    path: apps/frigate
    directory:
      recurse: true
    helm:
      chart: frigate
      repo: https://k8s-at-home.com/charts/
      version: 8.2.2
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: frigate
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
