apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: omada-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/slin86/argocd
    targetRevision: main
    path: helm/omada-controller
    helm:
      valueFiles:
        - apps/omada-controller/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: omada
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true