mongodb:
  enabled: false

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            OMADA_DB_HOST: mongodb.omada.svc.cluster.local
            OMADA_DB_PORT: "27017"
            OMADA_DB_USER: omada
            OMADA_DB_PASS: omada123
            OMADA_DB_NAME: omada

service:
  main:
    type: NodePort
    ports:
      main:
        port: 8043
        nodePort: 32043
        protocol: https
  omada-udp:
    enabled: true
    type: NodePort
    ports:
      omada-udp1:
        enabled: true
        protocol: udp
        port: 29810
        nodePort: 30981
  comm:
    enabled: true
    type: NodePort
    ports:
      comm:
        port: 8843
        nodePort: 31843
        protocol: tcp
  omada-tcp:
    enabled: true
    type: NodePort
    ports:
      omada-tcp1:
        port: 29811
        nodePort: 31011
      omada-tcp2:
        port: 29812
        nodePort: 31012
      omada-tcp3:
        port: 29813
        nodePort: 31013
      omada-tcp4:
        port: 29814
        nodePort: 31014
