mongodb:
  enabled: false

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            TZ: Europe/Berlin
            OMADA_DB_HOST: mongodb.omada.svc.cluster.local
            OMADA_DB_PORT: "27017"
            OMADA_DB_USER: omada
            OMADA_DB_PASS: omada123
            OMADA_DB_NAME: omada

service:
  main:
    type: NodePort