mongodb:
  enabled: false

workload:
  main:
    podSpec:
      hostNetwork: true  # ← Richtig hier!
      containers:
        main:
          env:
            CONTROLLER_HOSTNAME: 192.168.178.24
            OMADA_DB_HOST: mongodb.omada.svc.cluster.local
            OMADA_DB_PORT: "27017"
            OMADA_DB_USER: omada
            OMADA_DB_PASS: omada123
            OMADA_DB_NAME: omada
env:
  TZ: Europe/Berlin
