apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: grafana-admin
  namespace: infisical-operator
spec:
  hostAPI: http://infisical-infisical-standalone.infisical.svc.cluster.local:8080/api
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: homelab-ei-fj
        envSlug: prod
        secretsPath: /grafana
      credentialsRef:
        secretName: infisical-machine-identity
        secretNamespace: infisical-operator
  managedKubeSecretReferences:
    - secretName: grafana-admin
      secretNamespace: monitoring
      creationPolicy: Owner
