apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: nextcloud-admin
  namespace: infisical-operator
spec:
  # Service-Name verifizieren: kubectl get svc -n infisical
  hostAPI: http://infisical-infisical-standalone.infisical.svc.cluster.local:8080/api
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: homelab-ei-fj
        envSlug: prod
        secretsPath: /nextcloud/admin
      credentialsRef:
        secretName: infisical-machine-identity
        secretNamespace: infisical-operator
  managedKubeSecretReferences:
    - secretName: nextcloud-admin
      secretNamespace: nextcloud
      creationPolicy: Owner
