apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: nextcloud-db
  namespace: nextcloud
spec:
  hostAPI: http://infisical-infisical-standalone-infisical.infisical.svc.cluster.local:8080/api
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: homelab-ei-fj
        envSlug: prod
        secretsPath: /nextcloud/db
      credentialsRef:
        secretName: infisical-machine-identity
        secretNamespace: infisical-operator
  managedKubeSecretReferences:
    - secretName: nextcloud-db
      secretNamespace: nextcloud
      creationPolicy: Owner
