apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mqtt
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://k8s-at-home.com/charts/
    chart: mosquitto
    targetRevision: 4.8.2
    helm:
      values: |
        image:
          repository: eclipse-mosquitto
          tag: 2.0.14
        service:
          main:
            enabled: true
            type: NodePort
            ports:
              http:
                enabled: true
              mqtt:
                enabled: true
                port: 1884
                nodePort: 31883
          persistence:
            data:
              enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: mqtt
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
